version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: yike-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always

  redis:
    image: redis:5.0
    container_name: yike-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis:/data
    restart: always

  server:
    image: "ccr.ccs.tencentyun.com/yike/server:${DOCKER_SERVER_IMAGE_TAG}"
    container_name: yike-server
    environment:
      AUTO_MIGRATION="yes"
    volumes:
      - ./server/logs/app:/data/www/storage/logs
      - ./server/logs/nginx:/data/logs/nginx
    ports:
      - "8080:80"
    depends_on:
      - redis
      - tokenizer

  tokenizer:
    image: ccr.ccs.tencentyun.com/yike/tokenizer:1.0.0
    container_name: yike-tokenizer

  proxy:
    image: ccr.ccs.tencentyun.com/yike/proxy:1.0.1
    container_name: yike-proxy
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      - SERVER_NAME=hk-proxy.pengyyy.cn
      - ALLOW_IPS=43.139.110.102
    ports:
      - "80:80"
      - "443:443"
