name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        registry: ccr.ccs.tencentyun.com
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        ecr: auto
        logout: true
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ccr.ccs.tencentyun.com/yike/server:$(date +%s)
